apiVersion: apps/v1
kind: Deployment
metadata:
  name: agro-app
  namespace: agro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agro-app
  template:
    metadata:
      labels:
        app: agro-app
    spec:
      containers:
      - name: agro-app
        image: agreeculcure-web:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@postgres:5432/agro_db
