apiVersion: apps/v1
kind: Deployment
metadata:
  name: agree-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agree-app
  template:
    metadata:
      labels:
        app: agree-app
    spec:
      containers:
      - name: agree-app
        image: iscomarcuz/agreeculture-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@agree-postgres:5432/agree_db"
