apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agro-ingress
  namespace: agro
spec:
  rules:
  - host: agro.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: agro-app
            port:
              number: 5000
